name: smoke-test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Guix
        uses: PromyLoph/guix-install-action@master

      - name: Run smoke test via Guix
        run: guix shell -m manifest.scm -- clojure -A:xtdb -M test/smoke_test.clj trials/samples/repo
